# Generated by Django 3.0.9 on 2021-08-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_postulada',
            name='ciudad_nacimiento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='departamento_nacimiento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='pais_nacimiento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
