# Generated by Django 3.0.9 on 2021-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210803_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas_postulada',
            name='año_estudio_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_estudio_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_estudio_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_estudio_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='año_experiencia_9',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_estudio_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_estudio_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_estudio_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_estudio_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personas_postulada',
            name='mes_experiencia_9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
