# Generated by Django 3.0.9 on 2021-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210811_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_postulada',
            name='identificacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
