# Generated by Django 3.0.9 on 2021-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210826_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_1',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_10',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_2',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_3',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_4',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_5',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_6',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_7',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_8',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='funciones_y_logros_9',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
