# Generated by Django 3.0.9 on 2021-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20210826_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personas_postulada',
            name='cargo_9',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
