from django.db import models
from django.conf import settings
 #Create your models here.

class Cargo(models.Model):
    nombre=models.CharField(max_length=300, null=True)
    area=models.CharField(max_length=100, null=True, blank=True)
    ubicacion=models.CharField( max_length=100, null=True, blank=True)
    contrato=models.CharField(max_length=50, null=False, blank=True)
    jornada=models.TextField( null=True, blank=True)
    vacantes=models.IntegerField(default=0,null=True, blank=True)
    objetivo=models.TextField( null=True, blank=True)
    responsabilidades=models.TextField( null=True, blank=True)
    formacion=models.TextField( null=True, blank=True)
    sistemas_programas_herramientas=models.TextField( null=True, blank=True)
    experiencia=models.TextField( null=True, blank=True)
    idiomas=models.TextField( null=True, blank=True)
    conocimientos=models.TextField( null=True, blank=True)
    habilitado=models.BooleanField(default=False, null=True, blank=True)
    inicio_vacante=models.DateField(default='2012-09-04')
    vencimiento_vacante=models.DateField(default='2012-09-04')

    def __unicode__(self):
        return self.nombre

    def __str__(self):
        return self.nombre

class Personas_Postulada(models.Model):
    cargo=models.ForeignKey(Cargo,on_delete=models.SET_NULL, null=True)
    nombres=models.CharField(max_length=60, null=True)
    apellidos=models.CharField(max_length=80, null=True)
    identificacion=models.CharField(max_length=50, null=True)
    numero_identificacion=models.CharField(max_length=50, null=True)
    correo=models.EmailField()
    telefono=models.CharField(max_length=20, null=True)
    telefono_adicional=models.CharField(max_length=20, null=False)
    fecha_nacimiento=models.DateField()
    pais_nacimiento=models.CharField(max_length=100, null=True)
    departamento_nacimiento=models.CharField(max_length=100, null=True)
    ciudad_nacimiento=models.CharField(max_length=100, null=True)
    genero=models.CharField(max_length=10, null=True)
    soy_empleado=models.CharField(max_length=50, null=True)
    departamento_residencia=models.CharField(max_length=100, null=True)
    municipio_residencia=models.CharField(max_length=100, null=True)
    direccion=models.TextField(max_length=100, null=True)
    formacion_1=models.CharField(max_length=100, null=True)
    area_formacion_1=models.CharField(max_length=100, null=True)
    tarjeta_profesional_1=models.CharField(max_length=100, null=True)
    institucion_1=models.CharField(max_length=100, null=True)
    fecha_finalizacion_estudio_1=models.CharField(max_length=100, null=True)
    formacion_2=models.CharField(max_length=100, null=True)
    area_formacion_2=models.CharField(max_length=100, null=True)
    tarjeta_profesional_2=models.CharField(max_length=100, null=True)
    institucion_2=models.CharField(max_length=100, null=True)
    fecha_finalizacion_estudio_2=models.CharField(max_length=100, null=True)
    formacion_3=models.CharField(max_length=100, null=True)
    area_formacion_3=models.CharField(max_length=100, null=True)
    tarjeta_profesional_3=models.CharField(max_length=100, null=True)
    institucion_3=models.CharField(max_length=100, null=True)
    fecha_finalizacion_estudio_3=models.CharField(max_length=100, null=True)
    formacion_4=models.CharField(max_length=100, null=True)
    area_formacion_4=models.CharField(max_length=100, null=True)
    tarjeta_profesional_4=models.CharField(max_length=100, null=True)
    institucion_4=models.CharField(max_length=100, null=True)
    fecha_finalizacion_estudio_4=models.CharField(max_length=100, null=True)
    idioma_1=models.CharField(max_length=50, null=True)
    nivel_idioma_1=models.CharField(max_length=50, null=True)
    idioma_2=models.CharField(max_length=50, null=True)
    nivel_idioma_2=models.CharField(max_length=50, null=True)
    idioma_3=models.CharField(max_length=50, null=True)
    nivel_idioma_3=models.CharField(max_length=50, null=True)
    empresa_1=models.CharField(max_length=100, null=True)
    cargo_1=models.CharField(max_length=1000, null=True)
    funciones_y_logros_1=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_1=models.CharField(max_length=100, null=True)
    empresa_2=models.CharField(max_length=100, null=True)
    cargo_2=models.CharField(max_length=1000, null=True)
    funciones_y_logros_2=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_2=models.CharField(max_length=100, null=True)
    empresa_3=models.CharField(max_length=1000, null=True)
    cargo_3=models.CharField(max_length=1000, null=True)
    funciones_y_logros_3=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_3=models.CharField(max_length=100, null=True)
    empresa_4=models.CharField(max_length=100, null=True)
    cargo_4=models.CharField(max_length=1000, null=True)
    funciones_y_logros_4=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_4=models.CharField(max_length=100, null=True)
    empresa_5=models.CharField(max_length=100, null=True)
    cargo_5=models.CharField(max_length=1000, null=True)
    funciones_y_logros_5=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_5=models.CharField(max_length=100, null=True)
    empresa_6=models.CharField(max_length=100, null=True)
    cargo_6=models.CharField(max_length=1000, null=True)
    funciones_y_logros_6=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_6=models.CharField(max_length=100, null=True)
    empresa_7=models.CharField(max_length=100, null=True)
    cargo_7=models.CharField(max_length=1000, null=True)
    funciones_y_logros_7=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_7=models.CharField(max_length=100, null=True)
    empresa_8=models.CharField(max_length=100, null=True)
    cargo_8=models.CharField(max_length=1000, null=True)
    funciones_y_logros_8=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_8=models.CharField(max_length=100, null=True)
    empresa_9=models.CharField(max_length=100, null=True)
    cargo_9=models.CharField(max_length=1000, null=True)
    funciones_y_logros_9=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_9=models.CharField(max_length=100, null=True)
    empresa_10=models.CharField(max_length=1000, null=True)
    cargo_10=models.CharField(max_length=1000, null=True)
    funciones_y_logros_10=models.TextField(max_length=10000, null=True)
    fecha_finalizacion_experiencia_10=models.CharField(max_length=100, null=True)
    areas_de_interes=models.CharField(max_length=1000, null=True)
    otras_areas_de_interes=models.TextField(max_length=1000, null=True)
    ultimo_salario=models.IntegerField(default=0,null=True)
    aspiracion_salarial=models.CharField(max_length=100, null=True)
    archivo_HV=models.FileField(upload_to="App/",  null=True)
    referido_por=models.TextField(max_length=1000, null=True)
    comentarios=models.TextField(max_length=10000, null=True)
    revisado=models.BooleanField(default=False, null=True, blank=False)
    fecha_creacion=models.DateField(default='2012-09-04')

    def __str__(self):
        return self.correo
